desc:gjs: Launchpad Performance Gate

options:gmem=GJS_X_BRIDGE

@block

block_notes = floor(gmem[1000]);

while (
    midirecv(offset, msg1, msg23) ?
    (
        status = msg1 & $xF0;
        channel = msg1 & $x0F;

        is_note =
            status == $x90 ||
            status == $x80;

        is_launchpad_channel =
            channel == 9;

        pass_message = 1;

        is_note
        && is_launchpad_channel
        && block_notes == 1
        ? pass_message = 0;

        pass_message
        ? midisend(offset, msg1, msg23);
    );
);
